[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "--cov=app --cov-report=term-missing --cov-report=html --cov-fail-under=80 -v"

[tool.coverage.run]
source = ["app"]
omit = [
    "app/view/*",      # UI no testeable sin display
    "app/__init__.py",
    "*/tests/*"
]
[tool.coverage.report]
show_missing = true
skip_covered = false
